### ISSUE TITLE
Refactor JS in maintainer menu

### ISSUE THREAD

**Issue by HelloYeew** [Rurusetto/rurusetto#102]
I'm not good at JS but I think and I'm sure that the javascript in the maintainer menu (wiki/maintainer.html) can be refactor and make it smaller and less overhead.

**Comment by riyakushwaha** [comment]
Hii @HelloYeew , please assign this issue to me.

**Comment by HelloYeew** [comment]
@riyakushwaha assigned!

**Comment by HelloYeew** [comment]
Merged in #110
