### ISSUE TITLE
[Feature] Public API for getting list of rulesets

### ISSUE THREAD

**Issue by bbb651** [Rurusetto/rurusetto#115]
**Describe the new feature:**
A public api for getting the list of rulesets, and information about rulesets.  
For my use case, I'm building a simple ruleset manager, and I think it'll be better to use this existing collection of rulesets instead of creating another one.

**Proposal design of the feature:**
A rest api that returns a json, something like
`https://api.rulesets.info/v1/rulesets` => `{"rulesets": [{"name": "tau", "repository": "https://github.com/naoei/tau/releases/latest/download/osu.Game.Rulesets.Tau.dll", "download": "https://github.com/naoei/tau/releases/latest/download/osu.Game.Rulesets.Tau.dll"}, ...], "status": "200"}`

I found [this](https://github.com/Rurusetto/rurusetto/blob/a7327878fa493d6a93563abc927b39f0e81256ad/rurusetto/wiki/views.py#L757-L790) in the code but it doesn't look like it's actually being used anywhere..

**Comment by HelloYeew** [comment]
That's a good idea! Actually that code is worked now (https://rulesets.info/api/rulesets) but I currently focus on other feature that the rulesets creator requested. I will implemented on it. Thanks for the idea!

**Comment by HelloYeew** [comment]
Thanks for your patient! Now the first part of the API is available now! You can read the documentation in https://docs.rulesets.info/ and start trying it now! You can make a new issues if you have any suggestion on API or some feature suggection.
