### ISSUE TITLE
soyokaze! creator account

### ISSUE THREAD

**Issue by goodtrailer** [Rurusetto/rurusetto#122]
**Describe the new feature:**
Wasn't sure how else to tell you, but I made an account: https://rulesets.info/profile/7
From what you said here: https://github.com/goodtrailer/soyokaze/pull/34

**Comment by HelloYeew** [comment]
OK I assigned you as the rulesets creator now so you can edit your wiki page, make some wiki subpage and add recommend beatmap freely. Thanks for the response! If you want to contact me you can using the discord development server (link in readme) or search my discord `HelloYeew#2740`. Thanks for the response!
