### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by StalkyBoi43815** [Rurusetto/rurusetto#575]
It's actually crazy that osu! Lazer supports Linux but these plugins don't. I don't know about mac, as I don't use it, but if it isn't supported you should change that.

**Comment by HelloYeew** [comment]
If your "plugin" is the [rurusetto-addon](https://github.com/Flutterish/rurusetto-addon) please report issues there. This repository is for the [rurusetto website](https://rulesets.info/) only. Also the dlls provided in release should already support linux....
