### ISSUE TITLE
Auto generate the ruleset icon in dark mode and light mode

### ISSUE THREAD

**Issue by HelloYeew** [Rurusetto/rurusetto#86]
Most ruleset icon is white and it have a problem on showing in the light mode. Must make the new field in database to collect both dark icon and light icon. From Discord development server request that this must be create and detect automatically.

**Comment by siddhantdixit** [comment]
@HelloYeew  Can I work on this issue?

**Comment by HelloYeew** [comment]
@siddhantdixit Yes, you can!

**Comment by HelloYeew** [comment]
You can add the field to contain ruleset icon in light mode and dark mode in `Ruleset` model in `wiki` app.
