### ISSUE TITLE
Add error diagnostic to 500 error page

### ISSUE THREAD

**Issue by HelloYeew** [Rurusetto/rurusetto#87]
The 500 error is mainly from the codebase error so it will be good if in 500 error page can show the main diagnostic and can copy that error text to report in GitHub issues.

**Comment by ntachukwu** [comment]
How do I get the OSU! auth keys and ID? I can only see the option to download OSU! for windows and mac, I am on linux. https://osu.ppy.sh/home/download

**Comment by HelloYeew** [comment]
You must have an osu! account and you can generate OAuth ID and secret by create the app at the account setting page (https://osu.ppy.sh/home/account/edit) and osu! V1 API key you can get it from https://osu.ppy.sh/p/api.

**Comment by ntachukwu** [comment]
No download for linux.

**Comment by HelloYeew** [comment]
You can download osu!lazer (It's new osu! client with Linux support) in the release of the repositories! https://github.com/ppy/osu
