### ISSUE TITLE
Fix grammar in form helper

### ISSUE THREAD

**Issue by HelloYeew** [Rurusetto/rurusetto#91]
I don't know on this but I write all of the form helper myself and sometimes the grammar or the context is wrong. If something is wrong you can send the pull request and fix it.

**Comment by JeswinSunsi** [comment]
@HelloYeew There are grammatical errors on the site. I'll fork and fix them.

**Comment by HelloYeew** [comment]
> @HelloYeew There are grammatical errors on the site. I'll fork and fix them.

Thx!

**Comment by HelloYeew** [comment]
@JeswinSunsi Do you check all of the form helper in the website?
